---
title: "6_regressions_final"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lfe)
library(texreg)
```

In order: do business closures (all), business closures(filtered), SIP (all), SIP (closures)
```{r}
# depression

depression_sip_all <- felm(I(log(depression + 1 )) ~  
                 sip_first * year_indicator + no_sip_most_pop * year_indicator + 
               cases_per_100k +
                 unemploy_rate + debt_contract_relief + income_support + 
                 precip + temp + covid + lockdown|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v11)

depression_sip_part <- felm(I(log(depression + 1)) ~  
                 sip_first * year_indicator + no_sip_most_pop * year_indicator +
               cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + factor(income_support) + 
                 precip + temp + covid + lockdown|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v11_5)

depression_bus_all <- felm(I(log(depression + 1)) ~  
                 sip_first * year_indicator + busopen_most_pop * year_indicator +
               cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + factor(income_support) + 
                 precip + temp + log(covid+1) + lockdown|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v11)

depression_bus_part <- felm(I(log(depression + 1)) ~  
                 sip_first * year_indicator + busopen_most_pop * year_indicator +
               cases_per_100k +
                 log(unemploy_rate+1) + factor(debt_contract_relief) + factor(income_support) + 
                 log(precip+1) + temp + 
                 log(covid+1) + log(lockdown+1)|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v11_5)

htmlreg(l = list(depression_bus_all, depression_bus_part, depression_sip_all, depression_sip_part),
        digits = 4, include.ci = FALSE, file = "depression.doc")
```


```{r}

# With logs

depression_sip_all <- felm(I(log(depression + 1 )) ~  
                 sip_first * year_indicator + no_sip_most_pop * year_indicator + 
                 cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + factor(income_support) + 
                 precip + temp + log(covid + 1) + log(lockdown + 1)|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v11)

depression_sip_part <- felm(I(log(depression + 1)) ~  
                 sip_first * year_indicator + no_sip_most_pop * year_indicator +
               cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + factor(income_support) + 
                 precip + temp + log(covid+1) + log(lockdown+1)|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v11_5)

depression_bus_all <- felm(I(log(depression + 1)) ~  
                 sip_first * year_indicator + busopen_most_pop * year_indicator +
               cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + factor(income_support) + 
                 precip + temp + log(covid+1) + log(lockdown+1)|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v11)

depression_bus_part <- felm(I(log(depression + 1)) ~  
                 sip_first * year_indicator + busopen_most_pop * year_indicator +
               cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + factor(income_support) + 
                 precip + temp + 
                 log(covid+1) + log(lockdown+1)|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v11_5)

htmlreg(l = list(depression_bus_all, depression_bus_part, depression_sip_all, depression_sip_part),
        digits = 4, include.ci = FALSE, file = "depression.doc")
```
```{r}
# depression

anxiety_sip_all <- felm(I(log(anxiety + 1 )) ~  
                 sip_first * year_indicator + no_sip_most_pop * year_indicator + 
                 cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + factor(income_support) + 
                 precip + temp + log(covid + 1) + log(lockdown + 1)|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v11)

anxiety_sip_part <- felm(I(log(anxiety + 1)) ~  
                 sip_first * year_indicator + no_sip_most_pop * year_indicator +
               cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + factor(income_support) + 
                 precip + temp + log(covid+1) + log(lockdown+1)|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v11_5)

anxiety_bus_all <- felm(I(log(anxiety + 1)) ~  
                 sip_first * year_indicator + busopen_most_pop * year_indicator +
               cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + factor(income_support) + 
                 precip + temp + log(covid+1) + log(lockdown+1)|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v11)

anxiety_bus_part <- felm(I(log(anxiety + 1)) ~  
                 sip_first * year_indicator + busopen_most_pop * year_indicator +
               cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + factor(income_support) + 
                 precip + temp + 
                 log(covid+1) + log(lockdown+1)|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v11_5)

htmlreg(l = list(anxiety_bus_all, anxiety_bus_part, anxiety_sip_all, anxiety_sip_part),
        digits = 4, include.ci = FALSE, file = "anxiety.doc")
```
```{r}
panic_sip_all <- felm(I(log(panic + 1 )) ~  
                 sip_first * year_indicator + no_sip_most_pop * year_indicator + 
                 cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + factor(income_support) + 
                 precip + temp + log(covid + 1) + log(lockdown + 1)|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v11)

panic_sip_part <- felm(I(log(panic + 1)) ~  
                 sip_first * year_indicator + no_sip_most_pop * year_indicator +
               cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + factor(income_support) + 
                 precip + temp + log(covid+1) + log(lockdown+1)|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v11_5)

panic_bus_all <- felm(I(log(panic + 1)) ~  
                 sip_first * year_indicator + busopen_most_pop * year_indicator +
               cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + factor(income_support) + 
                 precip + temp + log(covid+1) + log(lockdown+1)|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v11)

panic_bus_part <- felm(I(log(panic + 1)) ~  
                 sip_first * year_indicator + busopen_most_pop * year_indicator +
               cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + factor(income_support) + 
                 precip + temp + 
                 log(covid+1) + log(lockdown+1)|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v11_5)

htmlreg(l = list(panic_bus_all, panic_bus_part, panic_sip_all, panic_sip_part),
        digits = 4, include.ci = FALSE, file = "panic.doc")
```
```{r}
mental_health_bus_part <- felm(I(log(mental_health + 1 )) ~  
                 sip_first * year_indicator + 
                busopen_most_pop * year_indicator + 
                school_first * year_indicator + online_only * year_indicator + 
                  hybrid * year_indicator + on_premises * year_indicator + 
                 cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + 
                   factor(income_support)  + 
                 precip + temp + log(covid + 1) + 
                   log(lockdown + 1)|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v14_5)
```

```{r}
htmlreg(l = list(anxiety_bus_all, crying_bus_all, depression_bus_all, lonely_bus_all, panic_bus_all, worry_bus_all, mental_health_bus_all), include.ci = FALSE, digits = 4, file = "mental_health_bus_prelim.doc")

htmlreg(l = list(anxiety_bus_part, crying_bus_part, depression_bus_part, lonely_bus_part, panic_bus_part, worry_bus_part, mental_health_bus_part), include.ci = FALSE, digits = 4, file = "mental_health_bus_prelim_5.doc")
```
```{r}
# Let's try some other stuff

yoga_bus_part <- felm(I(log(yoga + 1 )) ~  
                 sip_first * year_indicator + 
                busopen_most_pop * year_indicator + 
                school_pop_pct * year_indicator + online_only * year_indicator + 
                  hybrid * year_indicator + on_premises * year_indicator + 
                 cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + 
                   factor(income_support)  + 
                 precip + temp + log(covid + 1) + 
                   log(lockdown + 1)|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v14_5)

htmlreg(l = list(crying_bus_part, depression_bus_part,
                 lonely_bus_part, sad_bus_part, suicide_bus_part, tired_bus_part),
        include.ci = FALSE, digits = 4, file = "depression_prelim.doc")

htmlreg(l = list(anxiety_bus_part, nervous_bus_part, 
                 stress_bus_part, worry_bus_part, panic_bus_part),
        include.ci = FALSE, digits = 4, file = "anxiety_prelim.doc")


htmlreg(l = list(alcohol_bus_part, alcoholism_bus_part, 
                 cannabis_bus_part, cigarette_bus_part, drug_bus_part,
                 e_cig_bus_part, smoking_bus_part, substance_abuse_bus_part),
        include.ci = FALSE, digits = 4, file = "substance_prelim.doc")

htmlreg(l = list(exercise_bus_part, therapy_bus_part, 
                 yoga_bus_part),
        include.ci = FALSE, digits = 4, file = "coping_prelim.doc")
```
```{r}
# school only
yoga_bus_part <- felm(I(log(yoga + 1 )) ~  
                school_pop_pct * year_indicator + online_only * year_indicator + 
                  hybrid * year_indicator + other * year_indicator + 
                 cases_per_100k +
                 unemploy_rate + factor(debt_contract_relief) + 
                   factor(income_support)  + 
                 precip + temp + log(covid + 1) + 
                   log(lockdown + 1)|
                 factor(dma):factor(year) + factor(week)|0|dma, 
             data = searches_norm3_v14_5)
```


```{r}
# Replicating Brodeur et al

# weights = na.omit(searches_norm3_v14_5$pop),
#                   data = searches_norm3_v14_5 %>% filter(is.na(pop) == FALSE)

anxiety_1 <- felm(I(log(anxiety + 1)) ~ 
                        busclose_first * year_indicator + 
                        cases_per_100k|factor(week) + factor(dma):factor(year)|0|dma,
                  data = searches_norm3_v14_5)

anxiety_2 <- felm(I(log(anxiety + 1)) ~ 
                        busclose_first * year_indicator + 
                        busopen_most_pop * year_indicator + 
                        cases_per_100k|factor(week) + factor(dma):factor(year)|0|dma,
                        data = searches_norm3_v14_5)

anxiety_3 <- felm(I(log(anxiety + 1)) ~ 
                        busclose_first * year_indicator + 
                        busopen_most_pop * year_indicator + 
                        cases_per_100k + unemploy_rate|factor(week) + factor(dma):factor(year)|0|dma,
                        data = searches_norm3_v14_5)

anxiety_4 <- felm(I(log(anxiety + 1)) ~ 
                        busclose_first * year_indicator + 
                        busopen_most_pop * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip
                       |factor(week) + factor(dma):factor(year)|0|dma,
                        data = searches_norm3_v14_5)

anxiety_5 <- felm(I(log(anxiety + 1)) ~ 
                        busclose_first * year_indicator + 
                        busopen _most_pop * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1)
                       |factor(week) + factor(dma):factor(year)|0|dma,
                        data = searches_norm3_v14_5)

anxiety_6 <- felm(I(log(anxiety + 1)) ~ 
                        busclose_first * year_indicator + 
                        busopen_most_pop * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma):factor(year)|0|dma,
                        data = searches_norm3_v14_5)
anxiety_7 <- felm(I(log(anxiety + 1)) ~ 
                        busclose_first * year_indicator + 
                        busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma):factor(year)|0|dma,
                        data = searches_norm3_v14_5)

htmlreg(l = list(anxiety_1, anxiety_2, anxiety_3, anxiety_4, 
                 anxiety_5, anxiety_6, anxiety_7), include.ci = FALSE,
        digits = 4, file = "anxiety_multi.doc")



# depression_orig <- felm(I(log(depression + 1)) ~ 
#                         sip_first * year_indicator + 
#                         cases_per_100k|factor(week) + factor(dma):factor(year)|0|dma,
#                         data = searches_v21_5)


```

```{r}
# Running again w/ population weights

# weights = na.omit(searches_norm3_v14_5$pop),
#                   data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE)


depression_1 <- felm(I(log(depression + 1)) ~ 
                        busclose_first * year_indicator + 
                        cases_per_100k|factor(week) + factor(dma):factor(year)|0|dma,
                  weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

depression_2 <- felm(I(log(depression + 1)) ~ 
                        busclose_first * year_indicator + 
                        busopen_most_pop * year_indicator + 
                        cases_per_100k|factor(week) + factor(dma):factor(year)|0|dma,
                        weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

depression_3 <- felm(I(log(depression + 1)) ~ 
                        busclose_first * year_indicator + 
                        busopen_most_pop * year_indicator + 
                        cases_per_100k + unemploy_rate|factor(week) + factor(dma):factor(year)|0|dma,
                        weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

depression_4 <- felm(I(log(depression + 1)) ~ 
                        busclose_first * year_indicator + 
                        busopen_most_pop * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip
                       |factor(week) + factor(dma):factor(year)|0|dma,
                        weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

depression_5 <- felm(I(log(depression + 1)) ~ 
                        busclose_first * year_indicator + 
                        busopen_most_pop * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1)
                       |factor(week) + factor(dma):factor(year)|0|dma,
                        weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

depression_6 <- felm(I(log(depression + 1)) ~ 
                        busclose_first * year_indicator + 
                        busopen_most_pop * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma):factor(year)|0|dma,
                        weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))
depression_7 <- felm(I(log(depression + 1)) ~ 
                        busclose_first * year_indicator + 
                        busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma):factor(year)|0|dma,
                        weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_1, depression_2, depression_3, depression_4, 
                 depression_5, depression_6, depression_7), include.ci = FALSE,
        digits = 4, file = "depression_multi_weighted.doc")
```

```{r}
# Let's REWEIGHTTTT

searches_norm3_v15 <- searches_norm3_v14 %>%
        group_by(dma, year) %>%
        mutate(average_3_ann = mean(average_3, na.rm = TRUE)) %>% 
        ungroup() %>% 
        mutate(average_3_ratio = average_3 / average_3_ann) %>% 
        mutate(across(c(alcohol:TV, cannabis:lockdown,
                        alone:sad), ~ . * average_3 / average_3_ratio)) %>% 
         mutate(across(c(alcohol:TV, cannabis:lockdown,
                        alone:sad), ~ . * 100 / max(.)))

# read in dma_5
searches_norm3_v15_5 <- searches_norm3_v15 %>%
        filter(dma %in% dma_5)

# Graph

searches_norm3_v15_5 %>% 
        group_by(date) %>% 
        summarize(ratio = mean(average_3_ratio, na.rm = TRUE)) %>% 
        mutate(date = as_date(date)) %>% 
        ggplot(aes(x = date, y = ratio)) + 
          geom_line() +
          theme_classic() +
          labs(x = "Date", y = "Yearly SVI Ratio") + 
          scale_x_date(breaks = "6 months", date_labels = "%m/%y")

# Let's add in some other stuff for regions

northeast <- c("CT", "ME", "MA", "NH", "RI", "VT", "NY", "NJ", "DE", "PA")

midwest <- c("IL", "IN", "MI", "OH", "WI", "IA", "KS", "MN", "MO", "NE", "ND", "SD")

south <- c("FL", "GA", "MD", "NC", "SC", "VA", "DC", "WV", "AL", "KY", "MS", "TN", "AR",
           "LA", "TX", "OK")

west <- c("AZ", "CO", "ID", "MT", "NV", "NM", "UT", "WY", "AK", "CA", "HI", "OR", "WA")

searches_norm3_v17 <- searches_norm3_v15 %>% 
        mutate(region = ifelse(state %in% northeast, "northeast",
                               ifelse(state %in% midwest, "midwest",
                                      ifelse(state %in% south, "south", 
                                             ifelse(state %in% west, "west", state)))))

searches_norm3_v17_5 <- searches_norm3_v17 %>% 
        filter(dma %in% dma_5)







```


```{r}
# Do prcomp
pca_dep <- searches_norm3_v15_5 %>%
        select(crying, depression, lonely, sad, tired)

pca_weights_dep <- prcomp(pca_dep)

rotation_dep <- as_tibble(pca_weights_dep$rotation, rownames = "term")

pca_anx <- searches_norm3_v15_5 %>% 
        select(anxiety, nervous, stress, worry, panic)

pca_weights_anx <- prcomp(pca_anx)

rotation_anx <- as_tibble(pca_weights_anx$rotation, rownames = "term")

pca_substance <- searches_norm3_v15_5 %>%
        select(alcohol, alcoholism, cannabis, cigarette, drug, e_cig, substance_abuse,
               smoking)

pca_weights_sub <- prcomp(pca_substance)

rotation_sub <- as_tibble(pca_weights_sub$rotation, rownames = "term")
```


```{r}
# Depression for the preliminary paper

depression_sip <- felm(I(log(depression + 1 )) ~  
                 sip_first * year_indicator + 
                no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             data = searches_norm3_v15_5)

anxiety_sip <- felm(I(log(anxiety + 1 )) ~  
                 sip_first * year_indicator + 
                no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             data = searches_norm3_v15_5)

depression_sip_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     sip_first * year_indicator + 
                                     no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             data = searches_norm3_v15_5)

anxiety_sip_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  sip_first * year_indicator + 
                                     no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             data = searches_norm3_v15_5)

htmlreg(l = list(depression_sip, depression_sip_index, anxiety_sip, anxiety_sip_index),
        include.ci = FALSE, digits = 4, file = "sip.doc")
```
```{r}
# Population weights
depression_sip <- felm(I(log(depression + 1 )) ~  
                 sip_first * year_indicator + 
                no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip <- felm(I(log(anxiety + 1 )) ~  
                 sip_first * year_indicator + 
                no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

depression_sip_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     sip_first * year_indicator + 
                                     no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
            weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  sip_first * year_indicator + 
                                     no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_sip, depression_sip_index, anxiety_sip, anxiety_sip_index),
        include.ci = FALSE, digits = 4, file = "sip.doc")
```


```{r}
depression_bus <- felm(I(log(depression + 1 )) ~  
                 busclose_first * year_indicator + 
                busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             data = searches_norm3_v15_5)

anxiety_bus <- felm(I(log(anxiety + 1 )) ~  
                 busclose_first * year_indicator + 
                busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             data = searches_norm3_v15_5)

depression_bus_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     busclose_first * year_indicator + 
                                     busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             data = searches_norm3_v15_5)

anxiety_bus_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  busclose_first * year_indicator + 
                                     busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             data = searches_norm3_v15_5)

htmlreg(l = list(depression_bus, depression_bus_index, anxiety_bus, anxiety_bus_index),
        include.ci = FALSE, digits = 4, file = "bus.doc")
```
```{r}
depression_bus <- felm(I(log(depression + 1 )) ~  
                 busclose_first * year_indicator + 
                busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus <- felm(I(log(anxiety + 1 )) ~  
                 busclose_first * year_indicator + 
                busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

depression_bus_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     busclose_first * year_indicator + 
                                     busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  busclose_first * year_indicator + 
                                     busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_bus, depression_bus_index, anxiety_bus, anxiety_bus_index),
        include.ci = FALSE, digits = 4, file = "bus.doc")
```

```{r}

# Region FEs

depression_bus <- felm(I(log(depression + 1 )) ~  
                 busclose_first * year_indicator + 
                busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)  + 
                               factor(region):factor(month)|0|dma, 
             weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus <- felm(I(log(anxiety + 1 )) ~  
                 busclose_first * year_indicator + 
                busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year) + 
                               factor(region):factor(month)|0|dma, 
             weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

depression_bus_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     busclose_first * year_indicator + 
                                     busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year) + 
                               factor(region):factor(month)|0|dma, 
             weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  busclose_first * year_indicator + 
                                     busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year) + 
                               factor(region):factor(month)|0|dma, 
             weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_bus, depression_bus_index, anxiety_bus, anxiety_bus_index),
        include.ci = FALSE, digits = 4, file = "bus.doc")

```
```{r}
depression_sip <- felm(I(log(depression + 1 )) ~  
                 sip_first * year_indicator + 
                no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year) + 
                               factor(region):factor(month)|0|dma, 
             weights = na.omit(searches_norm3_v17_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip <- felm(I(log(anxiety + 1 )) ~  
                 sip_first * year_indicator + 
                no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year) + 
                               factor(region):factor(month)|0|dma, 
             weights = na.omit(searches_norm3_v17_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

depression_sip_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     sip_first * year_indicator + 
                                     no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year) + 
                               factor(region):factor(month)|0|dma, 
            weights = na.omit(searches_norm3_v17_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  sip_first * year_indicator + 
                                     no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year) + 
                               factor(region):factor(month)|0|dma, 
             weights = na.omit(searches_norm3_v17_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_sip, depression_sip_index, anxiety_sip, anxiety_sip_index),
        include.ci = FALSE, digits = 4, file = "sip.doc")
```
```{r}
# Total -- all things

depression_bus <- felm(I(log(depression + 1 )) ~  
                 busclose_first * year_indicator + 
                busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17$pop),
                  data = searches_norm3_v17 %>% filter(is.na(pop) == FALSE))

anxiety_bus <- felm(I(log(anxiety + 1 )) ~  
                 busclose_first * year_indicator + 
                busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17$pop),
                  data = searches_norm3_v17 %>% filter(is.na(pop) == FALSE))

depression_bus_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     busclose_first * year_indicator + 
                                     busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17$pop),
                  data = searches_norm3_v17 %>% filter(is.na(pop) == FALSE))

anxiety_bus_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  busclose_first * year_indicator + 
                                     busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17$pop),
                  data = searches_norm3_v17 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_bus, depression_bus_index, anxiety_bus, anxiety_bus_index),
        include.ci = FALSE, digits = 4, file = "bus.doc")
```
```{r}
depression_sip <- felm(I(log(depression + 1 )) ~  
                 sip_first * year_indicator + 
                no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17$pop),
                  data = searches_norm3_v17 %>% filter(is.na(pop) == FALSE))

anxiety_sip <- felm(I(log(anxiety + 1 )) ~  
                 sip_first * year_indicator + 
                no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17$pop),
                  data = searches_norm3_v17 %>% filter(is.na(pop) == FALSE))

depression_sip_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     sip_first * year_indicator + 
                                     no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
            weights = na.omit(searches_norm3_v17$pop),
                  data = searches_norm3_v17 %>% filter(is.na(pop) == FALSE))

anxiety_sip_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  sip_first * year_indicator + 
                                     no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17$pop),
                  data = searches_norm3_v17 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_sip, depression_sip_index, anxiety_sip, anxiety_sip_index),
        include.ci = FALSE, digits = 4, file = "sip.doc")
```
```{r}
# Traditional DID setup

depression_sip <- felm(I(log(depression + 1 )) ~  
                 sip_first:year_indicator + 
                no_sip_most_pop:year_indicator + 
                        online_only:year_indicator + 
                        hybrid:year_indicator + 
                        other:year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip <- felm(I(log(anxiety + 1 )) ~  
                 sip_first:year_indicator + 
                no_sip_most_pop:year_indicator + 
                        online_only:year_indicator + 
                        hybrid:year_indicator + 
                        other:year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

depression_sip_index <- felm(I(log(0.485*crying + 0.782*depression + 
                                0.127*lonely + 0.320*sad + 0.184*tired + 1)) ~ 
                                     sip_first:year_indicator + 
                                     no_sip_most_pop:year_indicator + 
                        online_only:year_indicator + 
                        hybrid:year_indicator + 
                        other:year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
            weights = na.omit(searches_norm3_v17_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip_index <- felm(I(log(0.485*crying + 0.782*depression + 
                                0.127*lonely + 0.320*sad + 0.184*tired + 1)) ~ 
                                  sip_first:year_indicator + 
                                     no_sip_most_pop:year_indicator + 
                        online_only:year_indicator + 
                        hybrid:year_indicator + 
                        other:year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_sip, depression_sip_index, anxiety_sip, anxiety_sip_index),
        include.ci = FALSE, digits = 4, file = "sip.doc")
```

```{r}
depression_bus <- felm(I(log(depression + 1 )) ~  
                 busclose_first:year_indicator + 
                                     busopen_most_pop:year_indicator + 
                        online_only:year_indicator + 
                        hybrid:year_indicator + 
                        other:year_indicator +
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus <- felm(I(log(anxiety + 1 )) ~  
                busclose_first:year_indicator + 
                                     busopen_most_pop:year_indicator + 
                        online_only:year_indicator + 
                        hybrid:year_indicator + 
                        other:year_indicator +
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

depression_bus_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     busclose_first:year_indicator + 
                                     busopen_most_pop:year_indicator + 
                        online_only:year_indicator + 
                        hybrid:year_indicator + 
                        other:year_indicator +
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                 busclose_first:year_indicator + 
                                     busopen_most_pop:year_indicator + 
                        online_only:year_indicator + 
                        hybrid:year_indicator + 
                        other:year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_bus, depression_bus_index, anxiety_bus, anxiety_bus_index),
        include.ci = FALSE, digits = 4, file = "bus.doc")
```
```{r}
# Denrmalized

depression_bus <- felm(I(log(depression + 1 )) ~  
                 busclose_first * year_indicator + 
                busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_v21_5$pop),
                  data = searches_v21_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus <- felm(I(log(anxiety + 1 )) ~  
                 busclose_first * year_indicator + 
                busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_v21_5$pop),
                  data = searches_v21_5 %>% filter(is.na(pop) == FALSE))

depression_bus_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     busclose_first * year_indicator + 
                                     busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_v21_5$pop),
                  data = searches_v21_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  busclose_first * year_indicator + 
                                     busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_v21_5$pop),
                  data = searches_v21_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_bus, depression_bus_index, anxiety_bus, anxiety_bus_index),
        include.ci = FALSE, digits = 4, file = "bus.doc")
```


```{r}
depression_sip <- felm(I(log(depression + 1 )) ~  
                 sip_first * year_indicator + 
                no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_v21_5$pop),
                  data = searches_v21_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip <- felm(I(log(anxiety + 1 )) ~  
                 sip_first * year_indicator + 
                no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_v21_5$pop),
                  data = searches_v21_5 %>% filter(is.na(pop) == FALSE))

depression_sip_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     sip_first * year_indicator + 
                                     no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
            weights = na.omit(searches_v21_5$pop),
                  data = searches_v21_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  sip_first * year_indicator + 
                                     no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_v21_5$pop),
                  data = searches_v21_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_sip, depression_sip_index, anxiety_sip, anxiety_sip_index),
        include.ci = FALSE, digits = 4, file = "sip.doc")
```

```{r}
# population percent

depression_sip <- felm(I(log(depression + 1 )) ~  
                 sip_pop_pct * year_indicator + 
                no_sip_pop_pct * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip <- felm(I(log(anxiety + 1 )) ~  
                 sip_pop_pct * year_indicator + 
                no_sip_pop_pct * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

depression_sip_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     sip_pop_pct * year_indicator + 
                                     no_sip_pop_pct * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
            weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  sip_pop_pct * year_indicator + 
                                     no_sip_pop_pct * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v15_5$pop),
                  data = searches_norm3_v15_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_sip, depression_sip_index, anxiety_sip, anxiety_sip_index),
        include.ci = FALSE, digits = 4, file = "sip.doc")
```

```{r}

depression_bus <- felm(I(log(depression + 1 )) ~  
                 busclose_pop_pct * year_indicator + 
                busopen_pop_pct * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus <- felm(I(log(anxiety + 1 )) ~  
                 busclose_pop_pct * year_indicator + 
                busopen_pop_pct * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

depression_bus_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     busclose_pop_pct * year_indicator + 
                                     busopen_pop_pct * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  busclose_pop_pct * year_indicator + 
                                     busopen_pop_pct * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v17_5$pop),
                  data = searches_norm3_v17_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_bus, depression_bus_index, anxiety_bus, anxiety_bus_index),
        include.ci = FALSE, digits = 4, file = "bus.doc")
```

```{r}
# RACE

depression_bus <- felm(I(log(depression + 1 )) ~  
                 busclose_first * year_indicator * black_pct + 
                busopen_most_pop * year_indicator * black_pct + 
                        online_only * year_indicator * black_pct + 
                        hybrid * year_indicator * black_pct + 
                        other * year_indicator * black_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus <- felm(I(log(anxiety + 1 )) ~  
                 busclose_first * year_indicator * black_pct + 
                busopen_most_pop * year_indicator * black_pct + 
                        online_only * year_indicator * black_pct + 
                        hybrid * year_indicator * black_pct + 
                        other * year_indicator * black_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

depression_bus_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     busclose_first * year_indicator * black_pct + 
                                     busopen_most_pop * year_indicator * black_pct + 
                        online_only * year_indicator * black_pct + 
                        hybrid * year_indicator * black_pct + 
                        other * year_indicator * black_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  busclose_first * year_indicator * black_pct + 
                                     busopen_most_pop * year_indicator * black_pct + 
                        online_only * year_indicator * black_pct + 
                        hybrid * year_indicator * black_pct + 
                        other * year_indicator * black_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_bus, depression_bus_index, anxiety_bus, anxiety_bus_index),
        include.ci = FALSE, digits = 4, file = "bus.doc")

```

```{r}
depression_sip <- felm(I(log(depression + 1 )) ~  
                 sip_first * year_indicator * black_pct + 
                no_sip_most_pop * year_indicator * black_pct + 
                        online_only * year_indicator * black_pct + 
                        hybrid * year_indicator * black_pct + 
                        other * year_indicator * black_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip <- felm(I(log(anxiety + 1 )) ~  
                  sip_first * year_indicator * black_pct + 
                no_sip_most_pop * year_indicator * black_pct + 
                        online_only * year_indicator * black_pct + 
                        hybrid * year_indicator * black_pct + 
                        other * year_indicator * black_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

depression_sip_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                      sip_first * year_indicator * black_pct + 
                no_sip_most_pop * year_indicator * black_pct + 
                        online_only * year_indicator * black_pct + 
                        hybrid * year_indicator * black_pct + 
                        other * year_indicator * black_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  sip_first * year_indicator * black_pct + 
                no_sip_most_pop * year_indicator * black_pct + 
                        online_only * year_indicator * black_pct + 
                        hybrid * year_indicator * black_pct + 
                        other * year_indicator * black_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_sip, depression_sip_index, anxiety_sip, anxiety_sip_index),
        include.ci = FALSE, digits = 4, file = "sip.doc")
```

```{r}
# White people
depression_bus <- felm(I(log(depression + 1 )) ~  
                 busclose_first * year_indicator * white_pct + 
                busopen_most_pop * year_indicator * white_pct + 
                        online_only * year_indicator * white_pct + 
                        hybrid * year_indicator * white_pct + 
                        other * year_indicator * white_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus <- felm(I(log(anxiety + 1 )) ~  
                 busclose_first * year_indicator * white_pct + 
                busopen_most_pop * year_indicator * white_pct + 
                        online_only * year_indicator * white_pct + 
                        hybrid * year_indicator * white_pct + 
                        other * year_indicator * white_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

depression_bus_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     busclose_first * year_indicator * white_pct + 
                                     busopen_most_pop * year_indicator * white_pct + 
                        online_only * year_indicator * white_pct + 
                        hybrid * year_indicator * white_pct + 
                        other * year_indicator * white_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  busclose_first * year_indicator * white_pct + 
                                     busopen_most_pop * year_indicator * white_pct + 
                        online_only * year_indicator * white_pct + 
                        hybrid * year_indicator * white_pct + 
                        other * year_indicator * white_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_bus, depression_bus_index, anxiety_bus, anxiety_bus_index),
        include.ci = FALSE, digits = 4, file = "bus.doc")

```

```{r}
depression_sip <- felm(I(log(depression + 1 )) ~  
                 sip_first * year_indicator * white_pct + 
                no_sip_most_pop * year_indicator * white_pct + 
                        online_only * year_indicator * white_pct + 
                        hybrid * year_indicator * white_pct + 
                        other * year_indicator * white_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip <- felm(I(log(anxiety + 1 )) ~  
                  sip_first * year_indicator * white_pct + 
                no_sip_most_pop * year_indicator * white_pct + 
                        online_only * year_indicator * white_pct + 
                        hybrid * year_indicator * white_pct + 
                        other * year_indicator * white_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

depression_sip_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                      sip_first * year_indicator * white_pct + 
                no_sip_most_pop * year_indicator * white_pct + 
                        online_only * year_indicator * white_pct + 
                        hybrid * year_indicator * white_pct + 
                        other * year_indicator * white_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  sip_first * year_indicator * white_pct + 
                no_sip_most_pop * year_indicator * white_pct + 
                        online_only * year_indicator * white_pct + 
                        hybrid * year_indicator * white_pct + 
                        other * year_indicator * white_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_sip, depression_sip_index, anxiety_sip, anxiety_sip_index),
        include.ci = FALSE, digits = 4, file = "sip.doc")
```

```{r}
# Politics

depression_bus <- felm(I(log(depression + 1 )) ~  
                 busclose_first * year_indicator * gop_pct + 
                busopen_most_pop * year_indicator * gop_pct + 
                        online_only * year_indicator * gop_pct + 
                        hybrid * year_indicator * gop_pct + 
                        other * year_indicator * gop_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus <- felm(I(log(anxiety + 1 )) ~  
                 busclose_first * year_indicator * gop_pct + 
                busopen_most_pop * year_indicator * gop_pct + 
                        online_only * year_indicator * gop_pct + 
                        hybrid * year_indicator * gop_pct + 
                        other * year_indicator * gop_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

depression_bus_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     busclose_first * year_indicator * gop_pct + 
                                     busopen_most_pop * year_indicator * gop_pct + 
                        online_only * year_indicator * gop_pct + 
                        hybrid * year_indicator * gop_pct + 
                        other * year_indicator * gop_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  busclose_first * year_indicator * gop_pct + 
                                     busopen_most_pop * year_indicator * gop_pct + 
                        online_only * year_indicator * gop_pct + 
                        hybrid * year_indicator * gop_pct + 
                        other * year_indicator * gop_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_bus, depression_bus_index, anxiety_bus, anxiety_bus_index),
        include.ci = FALSE, digits = 4, file = "bus.doc")
```

```{r}
depression_sip <- felm(I(log(depression + 1 )) ~  
                 sip_first * year_indicator * gop_pct + 
                no_sip_most_pop * year_indicator * gop_pct + 
                        online_only * year_indicator * gop_pct + 
                        hybrid * year_indicator * gop_pct + 
                        other * year_indicator * gop_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip <- felm(I(log(anxiety + 1 )) ~  
                  sip_first * year_indicator * gop_pct + 
                no_sip_most_pop * year_indicator * gop_pct + 
                        online_only * year_indicator * gop_pct + 
                        hybrid * year_indicator * gop_pct + 
                        other * year_indicator * gop_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

depression_sip_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                      sip_first * year_indicator * gop_pct + 
                no_sip_most_pop * year_indicator * gop_pct + 
                        online_only * year_indicator * gop_pct + 
                        hybrid * year_indicator * gop_pct + 
                        other * year_indicator * gop_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  sip_first * year_indicator * gop_pct + 
                no_sip_most_pop * year_indicator * gop_pct + 
                        online_only * year_indicator * gop_pct + 
                        hybrid * year_indicator * gop_pct + 
                        other * year_indicator * gop_pct + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_sip, depression_sip_index, anxiety_sip, anxiety_sip_index),
        include.ci = FALSE, digits = 4, file = "sip.doc")
```

```{r}
#Income 

depression_bus <- felm(I(log(depression + 1 )) ~  
                 busclose_first * year_indicator * median_income + 
                busopen_most_pop * year_indicator * median_income + 
                        online_only * year_indicator * median_income + 
                        hybrid * year_indicator * median_income + 
                        other * year_indicator * median_income + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus <- felm(I(log(anxiety + 1 )) ~  
                 busclose_first * year_indicator * median_income + 
                busopen_most_pop * year_indicator * median_income + 
                        online_only * year_indicator * median_income + 
                        hybrid * year_indicator * median_income + 
                        other * year_indicator * median_income + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

depression_bus_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                     busclose_first * year_indicator * median_income + 
                                     busopen_most_pop * year_indicator * median_income + 
                        online_only * year_indicator * median_income + 
                        hybrid * year_indicator * median_income + 
                        other * year_indicator * median_income + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

anxiety_bus_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  busclose_first * year_indicator * median_income + 
                                     busopen_most_pop * year_indicator * median_income + 
                        online_only * year_indicator * median_income + 
                        hybrid * year_indicator * median_income + 
                        other * year_indicator * median_income + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_bus, depression_bus_index, anxiety_bus, anxiety_bus_index),
        include.ci = FALSE, digits = 4, file = "bus.doc")
```

```{r}
depression_sip <- felm(I(log(depression + 1 )) ~  
                 sip_first * year_indicator * median_income + 
                no_sip_most_pop * year_indicator * median_income + 
                        online_only * year_indicator * median_income + 
                        hybrid * year_indicator * median_income + 
                        other * year_indicator * median_income + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip <- felm(I(log(anxiety + 1 )) ~  
                  sip_first * year_indicator * median_income + 
                no_sip_most_pop * year_indicator * median_income + 
                        online_only * year_indicator * median_income + 
                        hybrid * year_indicator * median_income + 
                        other * year_indicator * median_income + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

depression_sip_index <- felm(I(log(0.485 * crying + 0.782 * depression + 
                                0.127 * lonely + 0.320 * sad + 0.184 * tired + 1)) ~ 
                                      sip_first * year_indicator * median_income + 
                no_sip_most_pop * year_indicator * median_income + 
                        online_only * year_indicator * median_income + 
                        hybrid * year_indicator * median_income + 
                        other * year_indicator * median_income + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

anxiety_sip_index <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic + 1)) ~ 
                                  sip_first * year_indicator * median_income + 
                no_sip_most_pop * year_indicator * median_income + 
                        online_only * year_indicator * median_income + 
                        hybrid * year_indicator * median_income + 
                        other * year_indicator * median_income + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(depression_sip, depression_sip_index, anxiety_sip, anxiety_sip_index),
        include.ci = FALSE, digits = 4, file = "sip.doc")
```

```{r}
# State level
# pca

pca_dep <- hps_all_v11 %>%
        select(crying_norm, depression_norm, lonely_norm, sad_norm, tired_norm)

pca_weights_dep <- prcomp(pca_dep)

rotation_dep <- as_tibble(pca_weights_dep$rotation, rownames = "term")

pca_anx <- hps_all_v11 %>% 
        select(anxiety_norm, nervous_norm, stress_norm, worry_norm, panic_norm)

pca_weights_anx <- prcomp(pca_anx)

rotation_anx <- as_tibble(pca_weights_anx$rotation, rownames = "term")

```


```{r}
# State outcome regressions

depression_1 <- felm(log(hps_depression) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_2 <- felm(log(depression_norm) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_3 <- felm(I(log(0.353 * crying_norm + 
                                                   0.163 * depression_norm + 
                                                   0.529 * lonely_norm + 
                                                   0.586 * sad_norm + 
                                                   0.475 * tired_norm)) ~ 
                             factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_1 <- felm(log(hps_anxiety) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_2 <- felm(log(anxiety_norm) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_3 <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic)) ~ 
                             factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

htmlreg(l = list(depression_1, depression_2, depression_3, anxiety_1, anxiety_2, anxiety_3),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```

```{r}
depression_1 <- felm(log(hps_depression) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_2 <- felm(log(depression_norm) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_3 <- felm(I(log(0.353 * crying_norm + 
                                                   0.163 * depression_norm + 
                                                   0.529 * lonely_norm + 
                                                   0.586 * sad_norm + 
                                                   0.475 * tired_norm)) ~ 
                             factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_1 <- felm(log(hps_anxiety) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_2 <- felm(log(anxiety_norm) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_3 <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic)) ~ 
                             factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

htmlreg(l = list(depression_1, depression_2, depression_3, anxiety_1, anxiety_2, anxiety_3),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```

```{r}
depression_1 <- felm(log(hps_depression) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_2 <- felm(log(depression_norm) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_3 <- felm(I(log(0.353 * crying_norm + 
                                                   0.163 * depression_norm + 
                                                   0.529 * lonely_norm + 
                                                   0.586 * sad_norm + 
                                                   0.475 * tired_norm)) ~ 
                             stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_1 <- felm(log(hps_anxiety) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_2 <- felm(log(anxiety_norm) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_3 <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic)) ~ 
                             stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

htmlreg(l = list(depression_1, depression_2, depression_3, anxiety_1, anxiety_2, anxiety_3),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```

```{r}
depression_1 <- felm(log(hps_depression) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_2 <- felm(log(depression_norm) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_3 <- felm(I(log(0.353 * crying_norm + 
                                                   0.163 * depression_norm + 
                                                   0.529 * lonely_norm + 
                                                   0.586 * sad_norm + 
                                                   0.475 * tired_norm)) ~ 
                             factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_1 <- felm(log(hps_anxiety) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_2 <- felm(log(anxiety_norm) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_3 <- felm(I(log(0.924 * anxiety + 0.213 * nervous + 
                                0.133 * stress + 0.198 * worry + 0.211 * panic)) ~ 
                             factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

htmlreg(l = list(depression_1, depression_2, depression_3, anxiety_1, anxiety_2, anxiety_3),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```
```{r}
# Subpopulation -- black?

depression_1 <- felm(log(depression_black + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_1 <- felm(log(anxiety_agg_black + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)



htmlreg(l = list(depression_1,anxiety_1),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```

```{r}
# black - SIP

depression_1 <- felm(log(depression_black + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_1 <- felm(log(anxiety_agg_black + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)



htmlreg(l = list(depression_1,anxiety_1),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```


```{r}
# black - stringency

depression_1 <- felm(log(depression_black + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_1 <- felm(log(anxiety_agg_black + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)



htmlreg(l = list(depression_1,anxiety_1),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```
```{r}
# black - school

depression_1 <- felm(log(depression_black + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_1 <- felm(log(anxiety_agg_black + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)



htmlreg(l = list(depression_1,anxiety_1),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```

```{r}
# White

depression_1 <- felm(log(depression_white + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_1 <- felm(log(anxiety_agg_white + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)



htmlreg(l = list(depression_1,anxiety_1),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```

```{r}
depression_1 <- felm(log(depression_white + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_1 <- felm(log(anxiety_agg_white + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)



htmlreg(l = list(depression_1,anxiety_1),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```

```{r}

depression_1 <- felm(log(depression_white + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_1 <- felm(log(anxiety_agg_white + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)



htmlreg(l = list(depression_1,anxiety_1),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```

```{r}
depression_1 <- felm(log(depression_white + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_1 <- felm(log(anxiety_agg_white + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)



htmlreg(l = list(depression_1,anxiety_1),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```

```{r}
# Income and depression

depression_1 <- felm(log(depression_less25k + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_2 <- felm(log(depression_25to35k + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_3 <- felm(log(depression_35to50k + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_4 <- felm(log(depression_50to75k + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_5 <- felm(log(depression_75to100k + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_6 <- felm(log(depression_100to150k + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)


depression_7 <- felm(log(depression_150to200k + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)
# 
# 
# anxiety_1 <- felm(log(anxiety_agg_black + 1) ~ factor(c2_workplace_closing)  +
#                initclaims_combined + 
#                contclaims_combined + cases_per_100k_5day + 
#                factor(e1_income_support) + factor(e2_debt_contract_relief) + 
#                 log(covid_norm+1) + log(lockdown_norm+1)
#              |factor(period) + factor(state) + factor(year)|0|state,
#              data = hps_all_v11)



htmlreg(l = list(depression_1, depression_2, depression_3, depression_4, depression_5,
                 depression_6, depression_7),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```
```{r}
depression_1 <- felm(log(depression_less25k + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_2 <- felm(log(depression_25to35k + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_3 <- felm(log(depression_35to50k + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_4 <- felm(log(depression_50to75k + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_5 <- felm(log(depression_75to100k + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_6 <- felm(log(depression_100to150k + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)


depression_7 <- felm(log(depression_150to200k + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

htmlreg(l = list(depression_1, depression_2, depression_3, depression_4, depression_5,
                 depression_6, depression_7),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```

```{r}
depression_1 <- felm(log(depression_less25k + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_2 <- felm(log(depression_25to35k + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_3 <- felm(log(depression_35to50k + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_4 <- felm(log(depression_50to75k + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_5 <- felm(log(depression_75to100k + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_6 <- felm(log(depression_100to150k + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)


depression_7 <- felm(log(depression_150to200k + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

htmlreg(l = list(depression_1, depression_2, depression_3, depression_4, depression_5,
                 depression_6, depression_7),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```
```{r}
depression_1 <- felm(log(depression_less25k + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_2 <- felm(log(depression_25to35k + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_3 <- felm(log(depression_35to50k + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_4 <- felm(log(depression_50to75k + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_5 <- felm(log(depression_75to100k + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

depression_6 <- felm(log(depression_100to150k + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)


depression_7 <- felm(log(depression_150to200k + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

htmlreg(l = list(depression_1, depression_2, depression_3, depression_4, depression_5,
                 depression_6, depression_7),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```

```{r}
# Income and anxiety
anxiety_agg_1 <- felm(log(anxiety_agg_less25k + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_2 <- felm(log(anxiety_agg_25to35k + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_3 <- felm(log(anxiety_agg_35to50k + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_4 <- felm(log(anxiety_agg_50to75k + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_5 <- felm(log(anxiety_agg_75to100k + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_6 <- felm(log(anxiety_agg_100to150k + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)


anxiety_agg_7 <- felm(log(anxiety_agg_150to200k + 1) ~ factor(c2_workplace_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)



htmlreg(l = list(anxiety_agg_1, anxiety_agg_2, anxiety_agg_3, anxiety_agg_4, anxiety_agg_5,
                 anxiety_agg_6, anxiety_agg_7),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```
```{r}
anxiety_agg_1 <- felm(log(anxiety_agg_less25k + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_2 <- felm(log(anxiety_agg_25to35k + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_3 <- felm(log(anxiety_agg_35to50k + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_4 <- felm(log(anxiety_agg_50to75k + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_5 <- felm(log(anxiety_agg_75to100k + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_6 <- felm(log(anxiety_agg_100to150k + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)


anxiety_agg_7 <- felm(log(anxiety_agg_150to200k + 1) ~ factor(c6_stay_at_home_requirements)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

htmlreg(l = list(anxiety_agg_1, anxiety_agg_2, anxiety_agg_3, anxiety_agg_4, anxiety_agg_5,
                 anxiety_agg_6, anxiety_agg_7),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```
```{r}
anxiety_agg_1 <- felm(log(anxiety_agg_less25k + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_2 <- felm(log(anxiety_agg_25to35k + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_3 <- felm(log(anxiety_agg_35to50k + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_4 <- felm(log(anxiety_agg_50to75k + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_5 <- felm(log(anxiety_agg_75to100k + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_6 <- felm(log(anxiety_agg_100to150k + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)


anxiety_agg_7 <- felm(log(anxiety_agg_150to200k + 1) ~ factor(c1_school_closing)  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

htmlreg(l = list(anxiety_agg_1, anxiety_agg_2, anxiety_agg_3, anxiety_agg_4, anxiety_agg_5,
                 anxiety_agg_6, anxiety_agg_7),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```

```{r}
anxiety_agg_1 <- felm(log(anxiety_agg_less25k + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_2 <- felm(log(anxiety_agg_25to35k + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_3 <- felm(log(anxiety_agg_35to50k + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_4 <- felm(log(anxiety_agg_50to75k + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_5 <- felm(log(anxiety_agg_75to100k + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

anxiety_agg_6 <- felm(log(anxiety_agg_100to150k + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)


anxiety_agg_7 <- felm(log(anxiety_agg_150to200k + 1) ~ stringency_index  +
               initclaims_combined + 
               contclaims_combined + cases_per_100k_5day + 
               factor(e1_income_support) + factor(e2_debt_contract_relief) + 
                log(covid_norm+1) + log(lockdown_norm+1)
             |factor(period) + factor(state) + factor(year)|0|state,
             data = hps_all_v11)

htmlreg(l = list(anxiety_agg_1, anxiety_agg_2, anxiety_agg_3, anxiety_agg_4, anxiety_agg_5,
                 anxiety_agg_6, anxiety_agg_7),
        include.ci = FALSE, digits = 4, file = "hps.doc")
```

```{r}
# Therapy and coping mechs

exercise_bus <- felm(I(log(exercise + 1 )) ~  
                 busclose_first * year_indicator + 
                busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

sleep_bus <- felm(I(log(sleep + 1 )) ~  
                 busclose_first * year_indicator + 
                busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

therapy_bus <- felm(I(log(therapy + 1 )) ~  
                 busclose_first * year_indicator + 
                busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

yoga_bus <- felm(I(log(yoga + 1 )) ~  
                 busclose_first * year_indicator + 
                busopen_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))


htmlreg(l = list(exercise_bus, sleep_bus, therapy_bus, yoga_bus),
        include.ci = FALSE, digits = 4, file = "bus.doc")
```


```{r}
exercise_sip <- felm(I(log(exercise + 1 )) ~  
                 sip_first * year_indicator + 
                no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

sleep_sip <- felm(I(log(sleep + 1 )) ~  
                 sip_first * year_indicator + 
                no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

therapy_sip <- felm(I(log(therapy + 1)) ~ 
                                  sip_first * year_indicator + 
                                     no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
             weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

yoga_sip <- felm(I(log(yoga + 1)) ~ 
                                     sip_first * year_indicator + 
                                     no_sip_most_pop * year_indicator + 
                        online_only * year_indicator + 
                        hybrid * year_indicator + 
                        other * year_indicator + 
                        cases_per_100k + unemploy_rate + temp + precip + 
                       log(lockdown + 1) + log(covid + 1) + 
                       factor(income_support) + factor(debt_contract_relief)
                       |factor(week) + factor(dma) + factor(year)|0|dma, 
            weights = na.omit(searches_norm3_v18_5$pop),
                  data = searches_norm3_v18_5 %>% filter(is.na(pop) == FALSE))

htmlreg(l = list(exercise_sip, sleep_sip, therapy_sip, yoga_sip),
        include.ci = FALSE, digits = 4, file = "sip.doc")
```

