---
title: "9_verification"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(texreg)
library(lfe)
library(janitor)
library(lubridate)
library(openintro)
library(readxl)
library(ggpubr)
library(usmap)
library(RColorBrewer)
```

```{r}
# Read in the household pulse file

hps <- read_csv(
'data/verification/Indicators_of_Anxiety_or_Depression_Based_on_Reported_Frequency_of_Symptoms_During_Last_7_Days.csv', col_types = cols()) %>% 
  clean_names() %>% 
  select(-confidence_interval, -quartile_range, -low_ci, -high_ci, -phase, -time_period,
         -time_period_label) %>% 
  mutate(time_period_start_date = mdy(time_period_start_date),
         time_period_end_date = mdy(time_period_end_date)) %>%  
  rename('start_date' = 'time_period_start_date',
         'end_date' = 'time_period_end_date') %>% 
  pivot_wider(names_from = indicator, values_from = value) %>%
  clean_names() %>% 
  rename('hps_depression' = 'symptoms_of_depressive_disorder',
         'hps_anxiety' = 'symptoms_of_anxiety_disorder',
         'hps_either' = 'symptoms_of_anxiety_disorder_or_depressive_disorder')

hps_state <- hps %>%
  filter(state != "United States") %>%
  select(-subgroup, -group) %>%
  mutate(state_2 = state2abbr(state)) %>%
  select(-state)

hps_merged_norm <- expand_grid(hps_state, state_searches_norm) %>%
  mutate(state_3 = str_sub(state, start = 4, end = 5)) %>%
  filter(state_3 == state_2, 
         date + days(6) >= start_date,
         date <= end_date) %>%
  select(-state_3) %>%
  rename('state_code' = 'state') %>%
  rename('state' = 'state_2')

hps_merged <- expand_grid(hps_state, state_searches_v1) %>%
  mutate(state_3 = str_sub(state, start = 4, end = 5)) %>%
  filter(state_3 == state_2, 
         date + days(6) >= start_date,
         date <= end_date) %>%
  select(-state_3) %>%
  rename('state_code' = 'state') %>%
  rename('state' = 'state_2')

hps_merged_2 <- hps_merged %>% 
  group_by(start_date, end_date, state, hps_depression, hps_anxiety) %>% 
  summarize(across(anxiety:average_3, mean)) %>%
  select(-average, -average_3)

hps_merged_norm_v2 <- hps_merged_norm_v1 %>% 
  group_by(start_date, end_date, state, hps_depression, hps_anxiety) %>% 
  summarize(across(anxiety:average_3, mean)) %>%
  rename('anxiety_norm' = 'anxiety',
         'depression_norm' = 'depression')

hps_all_v1 <- left_join(hps_merged_norm_v2, hps_merged_2)


  
```

```{r}
depression_norm <- hps_all_v1 %>% 
  ggplot(mapping = aes(x = hps_depression, y = depression_norm)) + 
    geom_point() + 
    theme_classic() + 
    labs(x = "% People Reporting Depression (HPS)",
         y = "Depression SVI (normalized)") + 
    geom_smooth(method = 'lm')

depression <- hps_all_v1 %>% 
  ggplot(mapping = aes(x = hps_depression, y = depression)) + 
    geom_point() + 
    theme_classic() + 
    labs(x = "% People Reporting Depression (HPS)",
         y = "Depression SVI (un-normalized)") + 
    geom_smooth(method = 'lm')

depression_norm_log <- hps_all_v1 %>%
  ggplot(mapping = aes(x = log(hps_depression), y = log(depression_norm+1))) + 
    geom_point() + 
    theme_classic() + 
    labs(x = "Log % People Reporting Depression (HPS)",
         y = "Log Depression SVI (normalized)") + 
    geom_smooth(method = 'lm')

depression_log <- hps_all_v1 %>% 
  ggplot(mapping = aes(x = log(hps_depression), y = log(depression+1))) + 
    geom_point() + 
    theme_classic() + 
    labs(x = "Log % People Reporting Depression (HPS)",
         y = "Log Depression SVI (un-normalized)") + 
    geom_smooth(method = 'lm')

depression_total <- ggarrange(depression_norm, depression, depression_norm_log, depression_log, 
          labels = c("Normalized", "Un-Normalized", "Log Normalized", 
                     "Log Un-Normalized"), nrow = 1)

ggsave(depression_total, file = "depression_total.png", width = 10, height = 3,
       units = "in")

```

```{r}

test <- felm(depression_norm ~ hps_depression|state|0|state, data = hps_all_v1)

test2 <- felm(depression ~ hps_depression|state|0|state, data = hps_all_v1)

test3 <- felm(log(depression_norm+1) ~ log(hps_depression+1)|state|0|state, data = hps_all_v1)

test4 <- felm(log(depression + 1) ~ log(hps_depression + 1)|state|0|state, data = hps_all_v1)

htmlreg(l = list(test, test2, test3, test4), include.ci = FALSE, digits = 4, file = "depression_verif.doc")
```
```{r}
anxiety_norm <- hps_all_v1 %>% 
  filter(state == "NY") %>% 
  ggplot(mapping = aes(x = hps_anxiety, y = anxiety_norm)) + 
    geom_point() + 
    theme_classic() + 
    labs(x = "% People Reporting Anxiety (HPS)",
         y = "Anxiety SVI (normalized)") + 
    geom_smooth(method = 'lm')

anxiety <- hps_all_v1 %>% 
  ggplot(mapping = aes(x = hps_anxiety, y = anxiety)) + 
    geom_point() + 
    theme_classic() + 
    labs(x = "% People Reporting Anxiety (HPS)",
         y = "Anxiety SVI (Un-normalized)") + 
    geom_smooth(method = 'lm')

anxiety_norm_log <- hps_all_v1 %>% 
  ggplot(mapping = aes(x = log(hps_anxiety), y = log(anxiety_norm+1))) + 
    geom_point() + 
    theme_classic() + 
    labs(x = "% People Reporting Anxiety (HPS)",
         y = "Anxiety SVI (normalized)") + 
    geom_smooth(method = 'lm')

anxiety_log <- hps_all_v1 %>% 
  ggplot(mapping = aes(x = log(hps_anxiety), y = log(anxiety+1))) + 
    geom_point() + 
    theme_classic() + 
    labs(x = "% People Reporting Anxiety (HPS)",
         y = "Anxiety SVI (un-normalized)") + 
    geom_smooth(method = 'lm')

anxiety_total <- ggarrange(anxiety_norm, anxiety, anxiety_norm_log, anxiety_log, 
          labels = c("Normalized", "Un-Normalized", "Log Normalized", 
                     "Log Un-Normalized"), nrow = 1)

ggsave(anxiety_total, file = "anxiety_total_2.png", width = 10, height = 3,
       units = "in")

```

```{r}

test <- felm(depression_norm ~ hps_depression|0|0|state, data = hps_all_v3)

test2 <- felm(depression_norm ~ hps_depression|state|0|state, data = hps_all_v3)

test3 <- felm(log(depression_norm+1) ~ log(hps_depression)|0|0|state, data = hps_all_v3)

test4 <- felm(log(depression_norm+1) ~ log(hps_depression)|state|0|state, data = hps_all_v3)

htmlreg(l = list(test, test2, test3, test4), include.ci = FALSE, digits = 4, file = "depression_verif_part1.doc")

# part 2

test <- felm(depression ~ hps_depression|0|0|state, data = hps_all_v3)

test2 <- felm(depression ~ hps_depression|state|0|state, data = hps_all_v3)

test3 <- felm(log(depression+1) ~ log(hps_depression)|0|0|state, data = hps_all_v3)

test4 <- felm(log(depression+1) ~ log(hps_depression)|state|0|state, data = hps_all_v3)

htmlreg(l = list(test, test2, test3, test4), include.ci = FALSE, digits = 4, file = "depression_verif_part2.doc")

```

```{r}

```


```{r}
# alc 

alc <- read_excel('data/verification/state_alcsales_December2020.xlsx', sheet = "Data") %>%
  clean_names() %>% 
  select(-gallons, -ethanol, -population, -per_capita3yr, -pct_change) %>% 
  pivot_wider(names_from = 'beverage', values_from = 'per_capita') %>% 
  rename('spirits' = `1`,
         'wine' = `2`,
         'beer' = `3`,
         'all_alc' = `4`)

# read in alcohol norm

alc_2 <- left_join(alc, alcohol_norm, by = c("year", "month", "fips"))

```
```{r}
# LOOK AT THIS ... GRAPH

eq <- function(x,y) {
  m <- lm(y ~ x)
  as.character(
    as.expression(
      substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2,
                list(a = format(coef(m)[1], digits = 4),
                b = format(coef(m)[2], digits = 4),
                r2 = format(summary(m)$r.squared, digits = 3)))
    )
  )
}

alcohol_norm_graph <- alc_2 %>%
  ggplot(mapping = aes(x = log(all_alc+1), y = log(alcohol_norm+1))) + 
    geom_point() +
    theme_classic() + 
    labs(x = "Log Per-capita monthly alcohol consumption (gal)",
         y = "Log Adjusted Alcohol SVI (normalized vs. anchor)") + 
    geom_smooth(method='lm')

alcohol_graph <- alc_2 %>%
   ggplot(mapping = aes(x = log(all_alc + 1), y = log(alcohol + 1))) + 
    geom_point() +
    theme_classic() + 
    labs(x = "Log Per-capita monthly alcohol consumption (gal)",
         y = "Log Alcohol SVI (un-normalized)") + 
    geom_smooth(method='lm')
```

```{r}
# Test some regressions

test <- felm(alcohol_norm ~ all_alc|0|0|state, data = alcohol_final_v2)

test2 <- felm(alcohol_norm ~ all_alc|state|0|state, data = alcohol_final_v2)

test3 <- felm(log(alcohol_norm+1) ~ log(all_alc)|0|0|state, data = alcohol_final_v2)

test4 <- felm(log(alcohol_norm+1) ~ log(all_alc)|state|0|state, data = alcohol_final_v2)


# Part 2

test <- felm(alcohol ~ all_alc|0|0|state, data = alcohol_final_v2)

test2 <- felm(alcohol ~ all_alc|state|0|state, data = alcohol_final_v2)

test3 <- felm(log(alcohol+1) ~ log(all_alc)|0|0|state, data = alcohol_final_v2)

test4 <- felm(log(alcohol+1) ~ log(all_alc)|state|0|state, data = alcohol_final_v2)
```

```{r}
# join some populations in so we can do this in a population weighted way

state_dem <- read_csv('data/state_data/R12917460_SL040.csv', col_types = cols()) %>% 
  slice(2:n()) %>% 
  clean_names() %>% 
  select(state_fips_code, total_population_56)

alcohol_final_v2 <- left_join(alcohol_final, state_dem, by = c("fips" = "state_fips_code")) %>%
  mutate(total_population_56 = as.numeric(total_population_56)) 
```


```{r}
# Make a graph!

alcohol_weighted <- alcohol_final_v2 %>%
  group_by(year, month) %>% 
  summarize(all_alc = weighted.mean(all_alc, total_population_56),
            alcohol_norm = weighted.mean(alcohol_norm, total_population_56),
            alcohol = weighted.mean(alcohol, total_population_56)) %>% 
  mutate(date = mdy(paste(month, "01", year, sep = "-"))) %>% 
  ungroup() %>% 
  ggplot(aes(x = date)) + 
    geom_line(aes(y = all_alc, color = "Alcohol Consumption")) + 
    geom_line(aes(y = alcohol / max(alcohol) * 0.3, 
                  color = "Normalized GTrends (rescaled)")) + 
    geom_line(aes(y = alcohol_norm / max(alcohol_norm) * 0.3, 
                  color = "Un-normalized GTrends (rescaled)")) + 
    theme_classic() + 
    labs(x = "Date", y = "Gallons per Capita", title = "Alcohol Sales vs. Google Trends") + 
    theme(legend.position = "top") + 
    scale_color_manual(name = c("", "", ""),
                       values = c("Alcohol Consumption" = "blue",
                                  "Normalized GTrends (rescaled)" = "red",
                                  "Un-normalized GTrends (rescaled)" = "green"))
  
```

```{r}
# Tobacco?

tax_rev <- read_excel('data/verification/selected-monthly-sales-tax-collections-data.xlsx') %>%
  clean_names() %>%
  filter(tax_type == "Tobacco") %>% 
  select(-collection_month, -tax_type) %>%
  rename('state' = 'name',
         'month' = 'numeric_month') %>% 
  mutate(state = state2abbr(state)) %>%
  mutate(date = as_date(paste(year, month, '01', sep = "-")))

cig_tax <- read_csv('data/verification/Table_6694.csv') %>% 
  clean_names() %>% 
  filter(year %in% c(2019, 2020, 2021)) %>% 
  select(-data_source, -topic_description, -measure_description,
         -provision_group_description, -provision, -citation, -enacted_date,
         -effective_date, -comments) %>%
  mutate(state_2 = state2abbr(location_description)) %>% 
  select(-location_description) %>%
  mutate(start_date = 
           ifelse(quarter == 1, as_date(paste(year, "01-01", sep = "-")),
                  ifelse(quarter == 2, as_date(paste(year, "04-01", sep = "-")),
                         ifelse(quarter == 3, as_date(paste(year, "07-01")),
                                as_date(paste(year, "10-01", sep = "-"))))),
         end_date = 
           ifelse(quarter == 1, as_date(paste(year, "03-31", sep = "-")),
                           ifelse(quarter == 2, as_date(paste(year, "06-30", sep = "-")),
                                  ifelse(quarter == 3, as_date(paste(year, "09-30", sep = "-")),
                                         as_date(paste(year, "12-31", sep = "-")))))) %>% 
  mutate(start_date = as_date(start_date),
         end_date = as_date(end_date)) %>% 
  select(-quarter, -year)

cigs_combined <- expand_grid(tax_rev, cig_tax) %>% 
  filter(state == state_2,
         date >= start_date,
         date <= end_date) %>%
  select(-state_2, -start_date, -end_date) %>% 
  mutate(amount = as.numeric(amount)) %>% 
  mutate(packs_mil = amount/(value * 1000000))

# combine in the search data

smoking_state <- readRDS('smoking_state.rds')
  
  
```

```{r}
# Graphing HPS data vs. time-series search data

depression_graph <- hps_all_v3 %>% 
  group_by(state) %>% 
  arrange(start_date) %>% 
  ungroup() %>% 
  group_by(start_date) %>% 
  summarize(across(c(hps_depression:depression_norm, anxiety:depression), 
                   ~ weighted.mean(., w = pop))) %>% 
  ggplot(mapping = aes(x = start_date)) + 
    geom_line(aes(y = hps_depression, color = "Household Pulse")) + 
    geom_line(aes(y = depression_norm, color = "Normalized GTrends")) + 
    geom_line(aes(y = depression/2.5, color = "Un-normalized GTrends (re-scaled)")) + 
    theme_classic() + 
    theme(legend.position = "top") +
    labs(x = "Date", y = "HPS % reporting symptoms & Google SVI",
         title = "Depression GTrends vs. HPS") + 
    scale_color_manual(name = c("", "", ""),
                       values = c("Household Pulse" = "blue",
                                  "Normalized GTrends" = "red",
                                  "Un-normalized GTrends (re-scaled)" = "green")) + 
    scale_x_date(date_breaks = "3 months", date_labels = "%m/%y")

anxiety_graph <- hps_all_v3 %>% 
  group_by(state) %>% 
  arrange(start_date) %>% 
  ungroup() %>% 
  group_by(start_date) %>% 
  summarize(across(c(hps_depression:depression_norm, anxiety:depression), 
                   ~ weighted.mean(., w = pop))) %>% 
  ggplot(mapping = aes(x = start_date)) + 
    geom_line(aes(y = hps_anxiety, color = "Household Pulse")) + 
    geom_line(aes(y = anxiety_norm*1.1, color = "Normalized GTrends")) + 
    geom_line(aes(y = anxiety/2.05, color = "Un-normalized GTrends (re-scaled)")) + 
    theme_classic() + 
    theme(legend.position = "top") +
    labs(x = "Date", y = "HPS % reporting symptoms & Google SVI",
         title = "Anxiety GTrends vs. HPS") + 
    scale_color_manual(name = c("", "", ""),
                       values = c("Household Pulse" = "blue",
                                  "Normalized GTrends" = "red",
                                  "Un-normalized GTrends (re-scaled)" = "green")) + 
    scale_x_date(date_breaks = "3 months", date_labels = "%m/%y")
# lagged

hps_all_v1 %>% 
  group_by(state) %>% 
  arrange(start_date) %>% 
  mutate(across(c(anxiety_norm:depression_norm, anxiety:depression), ~ lag(., k = 2))) %>% 
  ungroup() %>% 
  group_by(start_date) %>%
  summarize(across(c(hps_depression:depression_norm, anxiety:depression), 
                   mean)) %>% 
  ggplot(mapping = aes(x = start_date)) + 
    geom_line(aes(y = hps_anxiety, color = "Household Pulse")) + 
    geom_line(aes(y = anxiety_norm, color = "Normalized GTrends")) + 
    geom_line(aes(y = anxiety/2.4, color = "Un-normalized GTrends (re-scaled)")) + 
    theme_classic() + 
    theme(legend.position = "top") + 
    labs(x = "Date", y = "HPS % reporting symptoms & Google SVI",
         title = "Anxiety") + 
    scale_color_manual(name = c("", "", ""),
                       values = c("Household Pulse" = "blue",
                                  "Normalized GTrends" = "red",
                                  "Un-normalized GTrends (re-scaled)" = "green")) + 
    scale_x_date(date_breaks = "3 months", date_labels = "%m/%y")

alcohol_final %>% 
  group_by(year, month) %>% 
  summarize(all_alc = mean(all_alc),
            alcohol = mean(alcohol),
            alcohol_norm = mean(alcohol_norm)) %>% 
  mutate(date = mdy(paste(month, "01", year, sep = "-"))) %>% 
  ggplot(aes(x = date)) + 
    geom_line(aes(y = all_alc, color = "Alcohol Consumption")) + 
    geom_line(aes(y = alcohol / max(alcohol) * 0.35, 
                  color = "Normalized GTrends (rescaled)")) + 
    geom_line(aes(y = alcohol_norm / max(alcohol_norm) * 0.35, 
                  color = "Un-normalized GTrends (rescaled)")) + 
    theme_classic() + 
    labs(x = "Date", y = "Gallons per Capita", title = "Alcohol") + 
    theme(legend.position = "top") + 
  scale_color_manual(name = c("", "", ""),
                       values = c("Alcohol Consumption" = "blue",
                                  "Normalized GTrends (rescaled)" = "red",
                                  "Un-normalized GTrends (rescaled)" = "green"))
    

```
```{r}
# Smoking -- read in the smoking final rds

smoking %>% 
  ggplot(mapping = aes(x = log(packs_per_capita+1), y = log(smoking_norm+1))) + 
    geom_point() + 
    geom_smooth(method = "lm") + 
    theme_classic() + 
    labs(x = "Imputed Packs per Capita", y = "Google Trends SVI (normalized)")

# Use this graph

smoking_graph<- smoking_final %>% 
  group_by(year, month) %>% 
  summarize(packs_per_capita = weighted.mean(packs_per_capita, total_pop),
            smoking = weighted.mean(smoking, total_pop),
            smoking_norm = weighted.mean(smoking_norm, total_pop)) %>% 
  mutate(date = mdy(paste(month, "01", year, sep = "-"))) %>% 
  ggplot(mapping = aes(x = date)) + 
    geom_line(aes(y = packs_per_capita, color = "Packs per Capita")) + 
    geom_line(aes(y = smoking/14, color = "Un-normalized GTrends (rescaled)")) + 
    geom_line(aes(y = smoking_norm/14, color = "Normalized GTrends (rescaled)")) + 
    theme_classic() + 
    labs(x = "Date", y = "Packs per Capita", title = "Imputed Cigarette Sales vs. Google Trends") + 
    theme(legend.position = "top") + 
    scale_color_manual(name = c("", "", ""),
                       values = c("Packs per Capita" = "blue",
                                  "Normalized GTrends (rescaled)" = "red",
                                  "Un-normalized GTrends (rescaled)" = "green"))


ggplot(aes(x = date)) + 
    geom_line(aes(y = all_alc, color = "Alcohol Consumption")) + 
    geom_line(aes(y = alcohol / max(alcohol) * 0.35, 
                  color = "Normalized GTrends (rescaled)")) + 
    geom_line(aes(y = alcohol_norm / max(alcohol_norm) * 0.35, 
                  color = "Un-normalized GTrends (rescaled)")) + 
    theme_classic() + 
    labs(x = "Date", y = "Gallons per Capita", title = "Alcohol") + 
    theme(legend.position = "top") + 
  scale_color_manual(name = c("", "", ""),
                       values = c("Alcohol Consumption" = "blue",
                                  "Normalized GTrends (rescaled)" = "red",
                                  "Un-normalized GTrends (rescaled)" = "green"))

# smoking_norm <- felm(smoking_norm ~ packs_per_capita|state|0|state, data = smoking)
# 
# smoking_log_norm <- felm(log(smoking_norm+1) ~ log(packs_per_capita+1)|state|0|state, data = smoking)
# 
# smoking_un <- felm(smoking ~ packs_per_capita|state|0|state, data = smoking)
# 
# smoking_log <- felm(log(smoking+1) ~ log(packs_per_capita+1)|state|0|state, data = smoking)
# 
# smoking_norm_nostate <- felm(smoking_norm ~ packs_per_capita|0|0|state, data = smoking)
# 
# smoking_log_norm_nostate <- felm(log(smoking_norm+1) ~ 
#                                    log(packs_per_capita+1)|0|0|state, data = smoking)
# 
# 
# 
# htmlreg(l = list(smoking_norm, smoking_un, smoking_log_norm, smoking_log,
#                  smoking_norm_nostate, smoking_log_norm_nostate), 
#         include.ci = FALSE, digits = 4, file = "smoking_verif.doc")

smoking_1 <- felm(smoking_norm ~ packs_per_capita|0|0|state, data = smoking_final)

smoking_2 <- felm(smoking_norm ~ packs_per_capita|state|0|state, data = smoking_final)

smoking_3 <- felm(log(smoking_norm+1) ~ log(packs_per_capita)|0|0|state, data = smoking_final)

smoking_4 <- felm(log(smoking_norm+1) ~ log(packs_per_capita)|state|0|state, data = smoking_final)

# part 2

smoking_1 <- felm(smoking ~ packs_per_capita|0|0|state, data = smoking_final)

smoking_2 <- felm(smoking ~ packs_per_capita|state|0|state, data = smoking_final)

smoking_3 <- felm(log(smoking+1) ~ log(packs_per_capita)|0|0|state, data = smoking_final)

smoking_4 <- felm(log(smoking+1) ~ log(packs_per_capita)|state|0|state, data = smoking_final)

```
```{r}
# Let's regress depression on anxiety

hps_1 <- felm(hps_depression ~ hps_anxiety|0|0|state, data = hps_all_v1)

hps_2 <- felm(depression_norm ~ anxiety_norm|0|0|state, data = hps_all_v1)

hps_3 <- felm(depression ~ anxiety|0|0|state, data = hps_all_v1)
```

```{r}

# Graphing?

hps_1 <- felm(log(depression_norm+1) ~ log(hps_depression):state|0|0|state,
              data = hps_all_v1)

hps_2 <- felm(log(anxiety_norm+1) ~ log(hps_anxiety):state|0|0|state,
              data = hps_all_v1)

depression_coef <- as_tibble(hps_1$coefficients, rownames = "state") %>% 
  filter(state != "(Intercept)") %>% 
  mutate(state = str_sub(state, start = 26))

anxiety_coef <-  as_tibble(hps_2$coefficients, rownames = "state") %>% 
  filter(state != "(Intercept)") %>% 
  mutate(state = str_sub(state, start = 23))

plot_usmap(data = depression_coef, values = "log(depression_norm + 1)") + 
  scale_fill_continuous(name = "Coefficient", type = "viridis") + 
  labs(title = "HPS vs. Google Trends Depression Searches")

plot_usmap(data = anxiety_coef, values = "log(anxiety_norm + 1)") + 
  scale_fill_continuous(name = "Coefficient", type = "viridis") + 
  labs(title = "HPS vs. Google Trends Anxiety Searches")

 
```

```{r}
# Check out therapy vs. therapy searches - hps all v4

therapy_graph <- hps_all_v4 %>% 
  group_by(start_date) %>% 
  summarize(across(medication:therapy_norm, ~ weighted.mean(., pop, na.rm = TRUE))) %>% 
  ggplot(aes(x = start_date)) + 
    geom_line(aes(y = counseling, color = "Household Pulse")) + 
    geom_line(aes(y = therapy_norm/7.2, color = "Normalized GTrends (rescaled)")) + 
    geom_line(aes(y = therapy/5.6, color = "Un-normalized GTrends (rescaled)")) + 
    theme_classic() +
    theme(legend.position = "top") + 
    labs(x = "Date", y = "HPS % receiving counseling/therapy in past month",
          title = "Therapy GTrends vs. HPS") + 
      scale_color_manual(name = c("", "", ""),
                       values = c("Household Pulse" = "blue",
                                  "Normalized GTrends (rescaled)" = "red",
                                  "Un-normalized GTrends (rescaled)" = "green")) +
    scale_x_date(date_breaks = "3 months", date_labels = "%m/%y")
  

therapy_1 <- felm(therapy_norm ~ counseling|0|0|state, data = hps_all_v4)

therapy_2 <- felm(therapy_norm ~ counseling|state|0|state, data = hps_all_v4)

therapy_3 <- felm(log(therapy_norm+1) ~ log(counseling)|0|0|state, data = hps_all_v4)

therapy_4 <- felm(log(therapy_norm+1) ~ log(counseling)|state|0|state, data = hps_all_v4)

htmlreg(l = list(therapy_1, therapy_2, therapy_3, therapy_4), include.ci = FALSE, digits = 4, file = "therapy_verif_part1.doc")

therapy_1 <- felm(therapy ~ counseling|0|0|state, data = hps_all_v4)

therapy_2 <- felm(therapy ~ counseling|state|0|state, data = hps_all_v4)

therapy_3 <- felm(log(therapy+1) ~ log(counseling)|0|0|state, data = hps_all_v4)

therapy_4 <- felm(log(therapy+1) ~ log(counseling)|state|0|state, data = hps_all_v4)


therapy_1 <- felm(log(therapy_norm+1) ~ log(counseling)|0|0|state, data = hps_all_v4)

therapy_2 <- felm(I(log(lag(therapy_norm, n = 1)+1)) ~ log(counseling)|0|0|state, data = hps_all_v4)

therapy_3 <- felm(I(log(lag(therapy_norm, n = 2)+1)) ~ log(counseling)|0|0|state, data = hps_all_v4)

therapy_4 <- felm(I(log(lag(therapy_norm, n = 3)+1)) ~ log(counseling)|0|0|state, data = hps_all_v4)

therapy_5 <- felm(I(log(lag(therapy_norm, n = 4)+1)) ~ log(counseling)|0|0|state, data = hps_all_v4)

htmlreg(l = list(therapy_1, therapy_2, therapy_3, therapy_4, therapy_5), include.ci = FALSE, digits = 4, file = "therapy_verif_part3.doc")

therapy_1 <- felm(log(therapy_norm+1) ~ log(counseling)|state|0|state, data = hps_all_v4)

therapy_2 <- felm(I(log(lag(therapy_norm, n = 1)+1)) ~ log(counseling)|state|0|state, data = hps_all_v4)

therapy_3 <- felm(I(log(lag(therapy_norm, n = 2)+1)) ~ log(counseling)|state|0|state, data = hps_all_v4)

therapy_4 <- felm(I(log(lag(therapy_norm, n = 3)+1)) ~ log(counseling)|state|0|state, data = hps_all_v4)

therapy_5 <- felm(I(log(lag(therapy_norm, n = 4)+1)) ~ log(counseling)|state|0|state, data = hps_all_v4)

htmlreg(l = list(therapy_1, therapy_2, therapy_3, therapy_4, therapy_5), include.ci = FALSE, digits = 4, file = "therapy_verif_part4.doc")


```
```{r}
# Some more exploratory stuff for HPS and medication

```


